using TrackingWebAPI.Models;

namespace TrackingWebAPI.Interfaces
{
    public interface IBULKVIRTUALBOOKING
    {
        Task<IEnumerable<BULKVIRTUALBOOKING>> GetAllBULKVIRTUALBOOKING();
        Task<BULKVIRTUALBOOKING> GetBULKVIRTUALBOOKINGById(int id);
        Task<BULKVIRTUALBOOKING> CreateBULKVIRTUALBOOKINGDetails(BULKVIRTUALBOOKING BULKVIRTUALBOOKING);
        Task<BULKVIRTUALBOOKING> UpdateBULKVIRTUALBOOKINGDetails(int id, BULKVIRTUALBOOKING BULKVIRTUALBOOKING);
        Task<BULKVIRTUALBOOKING> DeleteBULKVIRTUALBOOKINGDetails(int id);
    }
}
